# Generated by Django 4.1.3 on 2022-12-02 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0004_cv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CV',
        ),
    ]
