# Generated by Django 4.1.3 on 2022-12-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0005_delete_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('file', models.FileField(null=True, upload_to='upload_files')),
                ('content', models.TextField()),
            ],
        ),
    ]
