# Generated by Django 4.1.3 on 2022-12-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0008_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='if_follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cv',
            name='time',
            field=models.TimeField(default='2022-12-02 02:48:03'),
        ),
    ]
