# Generated by Django 4.1.3 on 2022-12-02 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0011_alter_cv_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='date',
        ),
    ]
