# Generated by Django 4.1.3 on 2022-12-02 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0014_remove_cv_date_cv_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='time',
        ),
        migrations.AddField(
            model_name='cv',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
