# Generated by Django 4.1.3 on 2022-12-02 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0015_remove_cv_time_cv_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='date'),
        ),
    ]
