# Generated by Django 4.1.3 on 2022-12-02 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0016_alter_cv_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CV',
        ),
    ]
