# Generated by Django 4.1.3 on 2022-12-02 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0017_delete_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('date', models.DateField(default=datetime.date.today)),
                ('file', models.FileField(null=True, upload_to='upload_files')),
                ('content', models.TextField()),
                ('if_follow', models.BooleanField(default=False)),
            ],
        ),
    ]
