# Generated by Django 4.1.3 on 2022-12-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0018_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='file',
        ),
    ]
