# Generated by Django 4.1.3 on 2022-12-04 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0019_remove_cv_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
