# Generated by Django 4.1.3 on 2022-12-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0020_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
                ('pwd', models.CharField(max_length=32)),
            ],
        ),
    ]
